##### CRUD USER

### Create User

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "id": "1",
  "name": "Marcio Cunha",
  "email": "marcao@gmail.com",
  "username": "Marcao",
  "password": "Senha_Inutel"
}

### Login User

POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "username": "Marcao",
  "password": "Senha_Inutel"
}

### Read All Users

GET http://localhost:3000/api/v1/users

### Read User

GET http://localhost:3000/api/v1/users/1

### Update user for PUT

PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
  "name": "Marcio Cunha",
  "email": "marcao@gmail.com",
  "username": "Marcao",
  "password": "Senha_Util"
}

### Update user for PATCH

PATCH http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
  "photo_profile": "https://images.unsplash.com/photo-1582070595814-fe36a8d39532?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bWFyY298ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
}

### Delete User

DELETE http://localhost:3000/api/v1/users/1
